### ISSUE TITLE
[BUG] java.lang.RuntimeException: Storage Type not detected for i8g.8xlarge

### ISSUE THREAD

**Issue by liangjun-jiang** [aws-samples/aws-emr-advisor#6]
**Describe the bug**
with emr-7.5.0 and the job_spark_pi event log, I am seeing this error:

24/12/06 15:08:31 ERROR AppAnalyzer: Failed in Analyzer AppEnvCostAnalyzer
java.lang.RuntimeException: Storage Type not detected for i8g.8xlarge
	at com.amazonaws.emr.api.AwsPricing$.$anonfun$getEc2ServicePrice$2(AwsPricing.scala:257)
	at scala.collection.immutable.List.map(List.scala:297)
	at com.amazonaws.emr.api.AwsPricing$.getEc2ServicePrice(AwsPricing.scala:243)
	at com.amazonaws.emr.api.AwsPricing$.getEmrAvailableInstances(AwsPricing.scala:309)
	at com.amazonaws.emr.spark.analyzer.AppEnvCostAnalyzer.analyze(AppEnvCostAnalyzer.scala:32)
	at com.amazonaws.emr.spark.analyzer.AppAnalyzer.analyze(AppAnalyzer.scala:9)
	at com.amazonaws.emr.spark.analyzer.AppAnalyzer.analyze$(AppAnalyzer.scala:8)
	at com.amazonaws.emr.spark.analyzer.AppEnvCostAnalyzer.analyze(AppEnvCostAnalyzer.scala:17)
	at com.amazonaws.emr.spark.analyzer.AppAnalyzer$.$anonfun$start$1(AppAnalyzer.scala:31)
	at com.amazonaws.emr.spark.analyzer.AppAnalyzer$.$anonfun$start$1$adapted(AppAnalyzer.scala:29)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at com.amazonaws.emr.spark.analyzer.AppAnalyzer$.start(AppAnalyzer.scala:29)
	at com.amazonaws.emr.spark.EmrSparkLogParser.analyze(EmrSparkLogParser.scala:38)
	at com.amazonaws.emr.SparkLogsAnalyzer$.delayedEndpoint$com$amazonaws$emr$SparkLogsAnalyzer$1(SparkLogsAnalyzer.scala:53)
	at com.amazonaws.emr.SparkLogsAnalyzer$delayedInit$body.apply(SparkLogsAnalyzer.scala:11)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)

**To Reproduce**
EMR release (e.g. emr-7.5.0) : 
1. run the job_spark_pi  event log with emr-7.5.0

**Expected behavior**
should not see this error

**Screenshots**

**Additional context**

**Comment by ripani-aws** [comment]
The issue is due to new Instance Types registered in the public pricing API without the storage type of the disk. The fix for this issue, will be pushed next week with some additional changes and improvements with the tool. I'll keep the issue open until the fix is merged.

**Comment by liangjun-jiang** [comment]
The reason I have to use the emr-7.5.0 is that I couldn't get the step function working properly with emr-7.3.0.  I am running this with Airflow EMR provider. 
Looking forward to seeing the changes.

**Comment by liangjun-jiang** [comment]
Can you make the change if it has been done? Really want to test this out.

**Comment by ripani-aws** [comment]
fixed in release 0.3.0
